name: deploy

on:
  push:
    branches:
      - main
jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.SSH_PASSWORD }}
          host: ${{ secrets.54.180.26.17 }}
          username: ${{ secrets.ubuntu }}
          port: ${{ secrets.22 }}
          script: |
           cd /home/ubuntu/READ-log-backend
           git pull main
           npm run build
           pm2 restart
